server:
  port: 8000
spring.config.import: "optional:consul:"  
spring:
  application:
    name: gateway
  config:
    import: 
        - optional:consul:
  cloud:
    consul:
      config:
        data-key: application.yml
        prefix: config
        format: yaml
        default-context: defaults
    loadbalancer:
      ribbon:
        enabled: false
      consul:
        enabled: true
      discovery:
        query-passing: true
    gateway:
      routes:
        - id: multiplication
          uri: lb://multiplication/
          predicates:
            - Path=/challenges/**,/attempts/**,/users/**
        - id: gamification
          uri: lb://gamification/
          predicates:
            - Path=/leaders
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: http://localhost:3000,http://localhost:8100
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST
logging:
  level:
    "[org.springframework.cloud.gateway.handler.predicate]": trace