### Get the secret ingredient.
GET https://localhost:5081/secret/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImdhbGt6Iiwic3ViIjoiZ2Fsa3oiLCJqdGkiOiJjODc5N2YxZCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjEwMDE3IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNDUiLCJodHRwczovL2xvY2FsaG9zdDo1MDgxIiwiaHR0cDovL2xvY2FsaG9zdDo1MjMwIl0sIm5iZiI6MTcxNjM5MDIzOCwiZXhwIjoxNzI0MzM5MDM4LCJpYXQiOjE3MTYzOTAyMzksImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.r08sUShtyyeBRrYAnIs2jzFzav1jna5trSFJvQXKC_U